export const userSheetID = '1eqVoLsZxGguEbRCC5rdI4iMVtQ7CK4T3uXRdx8zE3uw';
export const userSheetName = 'UserPlant';
export const userUrl = `https://opensheet.elk.sh/${userSheetID}/${userSheetName}`;
export const usageUrl = 'https://opensheet.elk.sh/1P8Frv1zvcuO3qt8seU-zMF0FV0TQHyKXLn9GNHVr6kI/MoveAllsum';
export const inventoryUrl = 'https://opensheet.elk.sh/1OtcgbmQdrI3gKJCGiDge6xuOsrT0GPxdKeFPjpvK3Rg/Sheet1';
export const mainsapUrl = 'https://opensheet.elk.sh/1CkfOIe2nDYBLs5aPGkPyZhOeqJkyS7UQ6tuMzxy-mfk/mainsap';
// New Data Sources (Generated by code.gs)
// REPORT_DIFF: "Report_Diff_Items"
// REPORT_DAILY: "Report_Daily_30Days"
// REPORT_MONTHLY: "Report_Monthly"
// REPORT_QUARTERLY: "Report_Quarterly"

// NOTE: Replace these with the actual "OpenSheet" URLs for your specific Spreadsheet ID and Sheet Names.
// Example format: https://opensheet.elk.sh/<SPREADSHEET_ID>/<SHEET_NAME>
// Since the user is using the same spreadsheet ID: 187t5gzeAtpt6kQN14UYOFF-LiWm_KoV0Jr6zogvGOe0

export const shotShipReportDiffUrl = 'https://opensheet.elk.sh/187t5gzeAtpt6kQN14UYOFF-LiWm_KoV0Jr6zogvGOe0/Report_Diff_Items';
export const shotShipReportDailyUrl = 'https://opensheet.elk.sh/187t5gzeAtpt6kQN14UYOFF-LiWm_KoV0Jr6zogvGOe0/Report_Daily_30Days';
export const shotShipReportMonthlyUrl = 'https://opensheet.elk.sh/187t5gzeAtpt6kQN14UYOFF-LiWm_KoV0Jr6zogvGOe0/Report_Monthly';
export const shotShipReportQuarterlyUrl = 'https://opensheet.elk.sh/187t5gzeAtpt6kQN14UYOFF-LiWm_KoV0Jr6zogvGOe0/Report_Quarterly';

// RAW DATA Source (Disabled - Using Report_Diff_Items)
// export const shotShipUrl = 'https://opensheet.elk.sh/187t5gzeAtpt6kQN14UYOFF-LiWm_KoV0Jr6zogvGOe0/Shotship';

export const shotShipSaveUrl = 'https://script.google.com/macros/s/AKfycbxZFx915ErNVTgTZgVULeDkbjDkCx8Q2bQkVZ73tD-zRu6Ob0_4PCVVSmUeNayHjNu8cg/exec';
export const shotShipRemarksUrl = 'https://opensheet.elk.sh/1fJRjIBMAnEDEhMIJBJ8HHwiTEZ9Z_wnB3TERQUeqgyY/ShotShipRemarks';

export const plantInfo = {
    "0301": { name: "นวนคร" },
    "0303": { name: "SA-สงขลา" },
    "0304": { name: "พระราม 3" },
    "0305": { name: "ราชบุรี" },
    "0307": { name: "สุราษฎร์" },
    "0309": { name: "นครราชสีมา" },
    "0310": { name: "SA-อุดร 1" },
    "0311": { name: "ศรีราชา" },
    "0312": { name: "พิษณุโลก" },
    "0313": { name: "ภูเก็ต" },
    "0315": { name: "SA-อยุธยา" },
    "0319": { name: "ขอนแก่น" },
    "0320": { name: "ลำปาง" },
    "0322": { name: "SA-อุดร 2" },
    "0323": { name: "SA-ลำลูกกา" },
    "0324": { name: "SA-ปัตตานี" },
    "0326": { name: "วิภาวดี 62" },
    "0362": { name: "SA-หนองแขม" },
    "0363": { name: "SA-ปัากเกร็ด" },
    "0364": { name: "SA-บางบัวทอง" },
    "0365": { name: "SA-สมุทรปราการ" },
    "0366": { name: "เชียงใหม่" },
    "0367": { name: "SA-ฉะเชิงเทรา" },
    "0368": { name: "SA-ร้อยเอ็ด" },
    "0369": { name: "ระยอง" }
};